### ISSUE TITLE
how the ListModelView can work with 'filters' query parameter?

### ISSUE THREAD

**Issue by horizon365** [hbakri/django-ninja-crud#408]
when get the list view, the query parameter filters must be blank ,or it says "Input should be None".
![图片](https://github.com/hbakri/django-ninja-crud/assets/17285011/4fb072f7-6935-4427-b8eb-0c17ece6e7b0)
![图片](https://github.com/hbakri/django-ninja-crud/assets/17285011/98609521-5edb-4ef8-82f0-07ddc55ff45a)

**Comment by horizon365** [comment]
sorry, i find another [releated issue.](https://github.com/hbakri/django-ninja-crud/issues/378) close it.

**Comment by horizon365** [comment]
@hbakri i am sorry, but the[ releated PR]( https://github.com/hbakri/django-ninja-crud/pull/361) seem doesn't release or publish.

**Comment by hbakri** [comment]
Hi @horizon365! Thanks for raising this issue, I apologize for the inconvenience caused by the bug.

You're correct that the current version (`0.4.1`) doesn't include the fix. I had addressed this in a [previous PR](https://github.com/hbakri/django-ninja-crud/pull/361) a long time ago but mistakenly held back the changes for a major release instead of releasing them promptly.

The good news is that version `1.0`, releasing this weekend, will include this fix along with a lot of other improvements and features! 🙌

As a workaround, you can use explicit `None` values for the query parameter filters when fetching the list view in Django Ninja's API docs.
